name: Deploy to npm
on:
    release:
        types: [created]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://npm.pkg.github.com/

            - name: Install dependencies
              run: yarn install

            - name: Lint code
              run: yarn lint

            - name: "Build code"
              run: yarn build

            - run: yarn publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
